// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// signC
double signC(double x);
RcppExport SEXP _miReact_signC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(signC(x));
    return rcpp_result_gen;
END_RCPP
}
// absC
double absC(double x);
RcppExport SEXP _miReact_absC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(absC(x));
    return rcpp_result_gen;
END_RCPP
}
// pmax_arma
arma::vec pmax_arma(arma::vec x, double bound);
RcppExport SEXP _miReact_pmax_arma(SEXP xSEXP, SEXP boundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type bound(boundSEXP);
    rcpp_result_gen = Rcpp::wrap(pmax_arma(x, bound));
    return rcpp_result_gen;
END_RCPP
}
// wcmod_basic
double wcmod_basic(const arma::vec p, const arma::vec n, const double alpha);
RcppExport SEXP _miReact_wcmod_basic(SEXP pSEXP, SEXP nSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(wcmod_basic(p, n, alpha));
    return rcpp_result_gen;
END_RCPP
}
// wcmodCPP
arma::mat wcmodCPP(arma::mat& var, arma::mat& pval, arma::mat& counts, double alpha);
RcppExport SEXP _miReact_wcmodCPP(SEXP varSEXP, SEXP pvalSEXP, SEXP countsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type var(varSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(wcmodCPP(var, pval, counts, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_miReact_signC", (DL_FUNC) &_miReact_signC, 1},
    {"_miReact_absC", (DL_FUNC) &_miReact_absC, 1},
    {"_miReact_pmax_arma", (DL_FUNC) &_miReact_pmax_arma, 2},
    {"_miReact_wcmod_basic", (DL_FUNC) &_miReact_wcmod_basic, 3},
    {"_miReact_wcmodCPP", (DL_FUNC) &_miReact_wcmodCPP, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_miReact(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
