# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

signC <- function(x) {
    .Call('_miReact_signC', PACKAGE = 'miReact', x)
}

absC <- function(x) {
    .Call('_miReact_absC', PACKAGE = 'miReact', x)
}

pmax_arma <- function(x, bound) {
    .Call('_miReact_pmax_arma', PACKAGE = 'miReact', x, bound)
}

wcmod_basic <- function(p, n, alpha) {
    .Call('_miReact_wcmod_basic', PACKAGE = 'miReact', p, n, alpha)
}

wcmod_basic2 <- function(idx, p, n, alpha) {
    .Call('_miReact_wcmod_basic2', PACKAGE = 'miReact', idx, p, n, alpha)
}

